-- casino.lua  (OpenComputers / OpenOS)
-- Generated by gen_casino.py - DO NOT EDIT BY HAND
-- Run:  python gen_casino.py

local component = require("component")
local event     = require("event")
local keyboard  = require("keyboard")
local shell     = require("shell")
local unicode   = require("unicode")

local gpu        = component.gpu
local MAX_W, MAX_H = gpu.maxResolution()
local W = math.min(120, MAX_W)
local H = math.min(40,  MAX_H)
gpu.setResolution(W, H)
local screenAddr = gpu.getScreen()

-- [CONFIG] ---------------------------------------------------
local CFG = {
    minBet    = 1,
    maxBet    = 10,
    startBal  = 1000,
    startPot  = 5000,
    startBank = 2500,
    saveFile  = shell.getWorkingDirectory() .. "/casino_save.dat",
}

local MULT = {
    diamond=50, nether_star=30, emerald=20,
    ender_pearl=15, gold_ingot=10, iron_ingot=5,
}

local ITEM_RU = {
    diamond     = "\208\144\208\187\208\188\208\176\208\183",
    nether_star = "\208\151\208\178\208\181\208\183\208\180\208\176",
    emerald     = "\208\152\208\183\209\131\208\188\209\128\209\131\208\180",
    ender_pearl = "\208\150\208\181\208\188\209\135\209\131\208\179",
    gold_ingot  = "\208\151\208\190\208\187\208\190\209\130\208\190",
    iron_ingot  = "\208\150\208\181\208\187\208\181\208\183\208\190",
}

local SYMBOLS = {"diamond","nether_star","emerald","ender_pearl","gold_ingot","iron_ingot"}

-- [ICONS] ----------------------------------------------------
local scriptDir = shell.getWorkingDirectory()
local loader, err = loadfile(scriptDir .. "/icons.lua")
if not loader then
    error("Cannot load icons.lua: " .. tostring(err), 0)
end
local icons = loader()
local ICW = icons.CHAR_WIDTH
local ICH = icons.CHAR_HEIGHT

-- [GPU PALETTE INIT] ----------------------------------------
-- Set the GPU's 8 palette slots to our custom icon/UI colors.
-- OC Tier 2 GPU: 8 palette slots (indices 0-7).
-- Palette matches OC_PALETTE in convert_icons.py exactly.
for i=1,#icons.PALETTE do
    pcall(gpu.setPaletteColor, i-1, icons.PALETTE[i])
end

-- [COLORS] -- must match OC_PALETTE indices in convert_icons.py ---
-- P[1]=0x111111 P[2]=0xEEEEEE P[3]=0x3366CC P[4]=0xDDAA11
-- P[5]=0x33BB33 P[6]=0xCC3333 P[7]=0x9944BB P[8]=0x888888
local C = {
    bg=0x111111, border=0x3366CC, title=0x3366CC, header=0x3366CC,
    text=0xEEEEEE, dim=0x888888, stat=0xDDAA11, win=0x33BB33,
    lose=0xCC3333, info=0x3366CC, mult=0xDDAA11,
    btnBet=0x3366CC, btnSpin=0x33BB33, btnExit=0xCC3333,
    slotBord=0x3366CC, slotBg=0x111111, avatar=0x3366CC, player=0xDDAA11,
}

-- [STATE] ----------------------------------------------------
local state = {
    balance=CFG.startBal, bet=CFG.minBet,
    pot=CFG.startPot, bank=CFG.startBank,
    reels={"diamond","emerald","gold_ingot"},
    spinning=false, msg="", msgClr=C.text,
}

-- [PERSISTENCE] ----------------------------------------------
local function saveGame()
    local f = io.open(CFG.saveFile,"w")
    if not f then return end
    f:write(state.balance.."\n"..state.bet.."\n"..state.pot.."\n"..state.bank.."\n")
    f:close()
end
local function loadGame()
    local f = io.open(CFG.saveFile,"r")
    if not f then return end
    state.balance = tonumber(f:read("*l")) or CFG.startBal
    state.bet     = tonumber(f:read("*l")) or CFG.minBet
    state.pot     = tonumber(f:read("*l")) or CFG.startPot
    state.bank    = tonumber(f:read("*l")) or CFG.startBank
    state.bet     = math.max(CFG.minBet, math.min(CFG.maxBet, state.bet))
    f:close()
end

-- [DRAW UTILS] -----------------------------------------------
local function put(x,y,text,fg,bg)
    gpu.setForeground(fg or C.text)
    gpu.setBackground(bg or C.bg)
    gpu.set(x,y,text)
end
local function fill(x,y,w,h,bg)
    gpu.setBackground(bg or C.bg)
    gpu.fill(x,y,w,h," ")
end
local function putCenter(y,text,fg,bg,x1,x2)
    x1=x1 or 1; x2=x2 or W
    local x=x1+math.floor((x2-x1+1-unicode.len(text))/2)
    if x<x1 then x=x1 end
    put(x,y,text,fg,bg)
end
local function drawBox(x,y,w,h,fg,bg)
    put(x,y,"+"..string.rep("-",w-2).."+",fg,bg)
    for dy=1,h-2 do put(x,y+dy,"|"..string.rep(" ",w-2).."|",fg,bg) end
    put(x,y+h-1,"+"..string.rep("-",w-2).."+",fg,bg)
end

-- Upper-half-block  U+2580  UTF-8: E2 96 80
local UPPER_BLOCK = "\226\150\128"

local function drawIcon(x,y,name)
    local icon=icons[name]
    if not icon then return end
    for ri,row in ipairs(icon) do
        local fg_s,bg_s=row[1],row[2]
        for col=1,ICW do
            gpu.setForeground(icons.PALETTE[fg_s:byte(col)])
            gpu.setBackground(icons.PALETTE[bg_s:byte(col)])
            gpu.set(x+col-1,y+ri-1,UPPER_BLOCK)
        end
    end
end

-- [LAYOUT] ---------------------------------------------------
local LW    = 22
local RX    = LW+2
local RW    = W-LW-1
local BOX_W = ICW+2
local BOX_H = ICH+2
local REELS_W = BOX_W*3+4
local REELS_X = LW+1+math.floor((W-LW-1-REELS_W)/2)
local BTN_Y   = H-2
local BET_Y   = H-3
local REELS_Y = BET_Y-1-BOX_H

-- [BUTTONS] --------------------------------------------------
local buttons={}
local function regBtn(x1,y1,x2,y2,action)
    table.insert(buttons,{x1=x1,y1=y1,x2=x2,y2=y2,action=action})
end
local function calcBetBtns()
    local defs={
        {"-10","bet:-10"},{"- 5","bet:-5"},{"-1","bet:-1"},
        {"\208\161\209\130\208\176\208\178\208\186\208\176 "..state.bet,"spin"},
        {"+1","bet:1"},{"+5","bet:5"},{"+10","bet:10"},
    }
    local totalW=-1
    for _,d in ipairs(defs) do totalW=totalW+unicode.len(d[1])+3 end
    local cx=LW+1+math.floor((W-LW-1-totalW)/2)
    local res={}
    for _,d in ipairs(defs) do
        local lbl="["..d[1].."]"
        local vl=unicode.len(lbl)
        table.insert(res,{x=cx,y=BTN_Y,label=lbl,vlen=vl,action=d[2],isSpin=(d[2]=="spin")})
        cx=cx+vl+1
    end
    return res
end
local function handleTouch(tx,ty)
    for _,b in ipairs(buttons) do
        if tx>=b.x1 and tx<=b.x2 and ty>=b.y1 and ty<=b.y2 then return b.action end
    end
end

-- [FRAME] ----------------------------------------------------
local function drawFrame()
    fill(1,1,W,H,C.bg)
    put(1,1,"+"..string.rep("-",W-2).."+",C.border,C.bg)
    for y=2,H-1 do put(1,y,"|",C.border,C.bg); put(W,y,"|",C.border,C.bg) end
    put(1,H,"+"..string.rep("-",W-2).."+",C.border,C.bg)
    for y=1,H do put(LW+1,y,"|",C.border,C.bg) end
    put(LW+1,1,"+",C.border,C.bg); put(LW+1,H,"+",C.border,C.bg)
end

-- [LEFT PANEL] -----------------------------------------------
local function drawLeft()
    local x=2
    put(x,2, "  \208\158\208\177\209\137\208\176\209\143 \208\184\208\189\209\132\208\190:",    C.header,C.bg)
    put(x,4, "\208\146\209\139 \208\184\208\179\209\128\208\176\208\181\209\130\208\181 \208\189\208\176 \209\129\208\178\208\190\208\185",       C.dim,   C.bg)
    put(x,5, "\209\129\209\130\209\128\208\176\209\133 \208\184 \209\128\208\184\209\129\208\186.",       C.dim,   C.bg)
    put(x,6, "\208\156\209\139 \208\189\208\181 \208\178\208\190\208\183\208\178\209\128\208\176\209\137\208\176\208\181\208\188",      C.dim,   C.bg)
    put(x,7, "\208\191\209\128\208\181\208\180\208\188\208\181\209\130\209\139.",      C.dim,   C.bg)
    put(x,9, "\208\146\209\129\208\181\208\179\208\190 \208\188\208\190\208\189\208\181\209\130:",       C.text,  C.bg)
    put(x,10,"  "..state.pot.." \208\188.",  C.stat,  C.bg)
    put(x,12,"\208\145\208\176\208\189\208\186 \208\178\209\139\208\191\208\187\208\176\209\130:",        C.text,  C.bg)
    put(x,13,"  "..state.bank.." \208\188.", C.stat,  C.bg)
    put(x,15,string.rep("-",LW-2),C.border,C.bg)
    put(x,16,"  __(^v^)__",      C.avatar,C.bg)
    put(x,18,"\208\152\208\179\209\128\208\190\208\186:",  C.text,  C.bg)
    local addr=""
    pcall(function() addr=tostring(component.computer.address()):sub(1,LW-4) end)
    put(x,19,"  "..addr,         C.player,C.bg)
    put(x,21,"\208\146\208\176\209\136 \208\177\208\176\208\187\208\176\208\189\209\129:", C.text,  C.bg)
    put(x,22,"  "..state.balance.." \208\188.",C.stat,C.bg)
    fill(x,23,LW-2,1,C.bg)
    if state.spinning then
        put(x,23,"\208\152\208\180\209\145\209\130 \208\184\208\179\209\128\208\176...",C.win,C.bg)
    elseif state.msg~="" then
        local m=state.msg
        if unicode.len(m)>LW-2 then m=unicode.sub(m,1,LW-2) end
        put(x,23,m,state.msgClr,C.bg)
    else
        put(x,23,"\208\147\208\190\209\130\208\190\208\178\208\190.",C.dim,C.bg)
    end
    put(3,H-2,"[ \208\146\209\139\209\133\208\190\208\180 ]",C.btnExit,C.bg)
end

-- [RIGHT PANEL] ----------------------------------------------
local function drawRight()
    putCenter(2,"* OpenCasino *",C.title,C.bg,LW+2,W-1)
    put(RX,4, "\208\152\208\189\209\132\208\190 \208\190 \208\178\209\139\208\184\208\179\209\128\209\139\209\136\208\176\209\133:",    C.header,C.bg)
    put(RX,5, "\208\146\209\139\208\184\208\179\209\128\209\139\209\136 = \209\129\209\130\208\176\208\178\208\186\208\176 * \208\177\208\190\208\189\209\131\209\129",C.text,  C.bg)
    put(RX,6, "\208\159\208\190 \208\186\209\128\208\176\209\143\208\188 x1          \208\160\209\143\208\180\208\190\208\188 x2",    C.info,  C.bg)
    put(RX,8, "\208\150\208\181\208\187\208\181\208\183\208\190 x5   \208\151\208\190\208\187\208\190\209\130\208\190 x10   \208\150\208\181\208\188\209\135\209\131\208\179 x15",   C.mult,  C.bg)
    put(RX,9, "\208\152\208\183\209\131\208\188\209\128\209\131\208\180 x20  \208\151\208\178\208\181\208\183\208\180\208\176 x30   \208\144\208\187\208\188\208\176\208\183 x50",  C.mult,  C.bg)
    put(RX,10,"\208\156\208\184\208\189. \209\129\209\130\208\176\208\178\208\186\208\176:".." "..CFG.minBet.." \208\188.".."   ".."\208\156\208\176\208\186\209\129. \209\129\209\130\208\176\208\178\208\186\208\176:".." "..CFG.maxBet.." \208\188.",C.dim,C.bg)
end

-- [REELS] ----------------------------------------------------
local function drawReels()
    for i=1,3 do
        local bx=REELS_X+(i-1)*(BOX_W+2)
        drawBox(bx,REELS_Y,BOX_W,BOX_H,C.slotBord,C.bg)
        fill(bx+1,REELS_Y+1,ICW,ICH,C.slotBg)
        drawIcon(bx+1,REELS_Y+1,state.reels[i])
    end
end

-- [BET BAR] --------------------------------------------------
local function drawBetBar()
    fill(LW+2,BET_Y-1,W-LW-2,1,C.bg)
    putCenter(BET_Y-1,"\208\154\209\128\209\131\209\130\208\184\208\188 \208\189\208\176".." "..state.bet.." \208\188.",C.text,C.bg,LW+2,W-1)
    local btns=calcBetBtns()
    buttons={}
    regBtn(3,H-2,unicode.len("[ \208\146\209\139\209\133\208\190\208\180 ]")+2,H-2,"exit")
    fill(LW+2,BTN_Y,W-LW-2,1,C.bg)
    for _,b in ipairs(btns) do
        put(b.x,b.y,b.label,b.isSpin and C.btnSpin or C.btnBet,C.bg)
        regBtn(b.x,b.y,b.x+b.vlen-1,b.y,b.action)
    end
end

local function redraw()
    drawFrame(); drawLeft(); drawRight(); drawReels(); drawBetBar()
end
local function partRedraw()
    drawLeft(); drawReels(); drawBetBar()
end

-- [GAME LOGIC] -----------------------------------------------
local function checkWin(r)
    local a,b,c=r[1],r[2],r[3]
    if a==b and b==c then
        local m=MULT[a] or 5
        return m, "\208\162\209\128\208\184 "..ITEM_RU[a].."!  \208\145\208\190\208\189\209\131\209\129 x"..m
    end
    if a==b or b==c then return 2,"\208\148\208\178\208\176 \209\128\209\143\208\180\208\190\208\188!  \208\145\208\190\208\189\209\131\209\129 x2" end
    if a==c          then return 1,"\208\148\208\178\208\176 \208\191\208\190 \208\186\209\128\208\176\209\143\208\188!  \208\145\208\190\208\189\209\131\209\129 x1" end
    return 0,"\208\157\208\181 \208\191\208\190\208\178\208\181\208\183\208\187\208\190..."
end

local function animSpin(final)
    state.spinning=true
    local stops={12,16,20}
    for step=1,20 do
        for i=1,3 do
            state.reels[i]=(step<stops[i]) and SYMBOLS[math.random(#SYMBOLS)] or final[i]
        end
        drawReels(); drawLeft(); os.sleep(0.05)
    end
    state.reels=final; state.spinning=false
end

local function doSpin()
    if state.spinning then return end
    if state.balance<state.bet then
        state.msg="\208\156\208\176\208\187\208\190 \208\188\208\190\208\189\208\181\209\130!"; state.msgClr=C.lose; partRedraw(); return
    end
    state.balance=state.balance-state.bet
    state.pot=state.pot+state.bet
    state.bank=state.bank+math.floor(state.bet*0.4)
    state.msg=""
    local final={}
    for i=1,3 do final[i]=SYMBOLS[math.random(#SYMBOLS)] end
    animSpin(final)
    local mult,msg=checkWin(final)
    if mult>0 then
        local gain=state.bet*mult
        state.balance=state.balance+gain
        state.bank=math.max(0,state.bank-gain)
        state.msg=msg.." \208\188.!"; state.msgClr=C.win
    else
        state.msg=msg; state.msgClr=C.lose
    end
    saveGame(); partRedraw()
end

local function changeBet(d)
    state.bet=math.max(CFG.minBet,math.min(CFG.maxBet,state.bet+d))
end

-- [MAIN LOOP] ------------------------------------------------
local function main()
    math.randomseed(os.time())
    loadGame()
    gpu.setBackground(C.bg); gpu.fill(1,1,W,H," ")
    redraw()
    while true do
        local etype,p1,p2,p3=event.pull()
        if etype=="touch" and p1==screenAddr then
            local a=handleTouch(p2,p3)
            if a=="exit" then break
            elseif a=="spin" then doSpin()
            elseif a and a:sub(1,4)=="bet:" then
                changeBet(tonumber(a:sub(5)) or 0); drawBetBar()
            end
        elseif etype=="key_down" then
            local code=p3
            if code==keyboard.keys.space or code==keyboard.keys.enter then doSpin()
            elseif code==keyboard.keys.left  then changeBet(-1); drawBetBar()
            elseif code==keyboard.keys.right then changeBet(1);  drawBetBar()
            elseif code==keyboard.keys.q     then break
            end
        elseif etype=="interrupted" then break
        end
    end
    saveGame()
    gpu.setBackground(C.bg); gpu.setForeground(C.text)
    gpu.fill(1,1,W,H," ")
    gpu.set(1,1,"Bye!")
end

main()
