#!/usr/bin/env python3
"""
gen_casino.py
Generates casino.lua for OpenComputers / OpenOS.

All Cyrillic (Russian) strings are encoded as Lua decimal byte-escapes
so the output .lua file is 100% pure ASCII and safe for OC's strict Lua parser.

Run this script whenever you change the casino code or Russian text.
"""

import os

# ─── helper ───────────────────────────────────────────────────
def r(s):
    """Python string -> Lua string literal with \\NNN escapes for every
    non-ASCII byte.  Result is pure ASCII: safe for OC Lua."""
    out = '"'
    for b in s.encode("utf-8"):
        if 32 <= b <= 126 and chr(b) not in ('"', "\\"):
            out += chr(b)
        else:
            out += f"\\{b}"
    out += '"'
    return out

# ─── all Russian / Unicode UI strings ─────────────────────────
S = {
    # left panel
    "gen_info":    r("  Общая инфо:"),
    "risk1":       r("Вы играете на свой"),
    "risk2":       r("страх и риск."),
    "noret1":      r("Мы не возвращаем"),
    "noret2":      r("предметы."),
    "total":       r("Всего монет:"),
    "bank":        r("Банк выплат:"),
    "avatar":      r("  __(^v^)__"),
    "player_lbl":  r("Игрок:"),
    "balance_lbl": r("Ваш баланс:"),
    "spinning":    r("Идёт игра..."),
    "ready":       r("Готово."),
    "exit_btn":    r("[ Выход ]"),
    # right panel
    "title":       r("* OpenCasino *"),
    "win_hdr":     r("Инфо о выигрышах:"),
    "win_formula": r("Выигрыш = ставка * бонус"),
    "w_edges":     r("По краям x1          Рядом x2"),
    "row_iron":    r("Железо x5   Золото x10   Жемчуг x15"),
    "row_pearl":   r("Изумруд x20  Звезда x30   Алмаз x50"),
    "min_bet":     r("Мин. ставка:"),
    "max_bet":     r("Макс. ставка:"),
    "spin_for":    r("Крутим на"),
    "cur":         r(" м."),
    # item names (used in win messages)
    "diamond":     r("Алмаз"),
    "nether_star": r("Звезда"),
    "emerald":     r("Изумруд"),
    "ender_pearl": r("Жемчуг"),
    "gold_ingot":  r("Золото"),
    "iron_ingot":  r("Железо"),
    # bet button spin label prefix
    "stavka":      r("Ставка "),
    # game messages
    "no_coins":    r("Мало монет!"),
    "no_luck":     r("Не повезло..."),
    "w_adj_msg":   r("Два рядом!  Бонус x2"),
    "w_edge_msg":  r("Два по краям!  Бонус x1"),
    "three_pfx":   r("Три "),
    "bonus_pfx":   r("!  Бонус x"),
    "coin_sfx":    r(" м.!"),
}

# ─── generate casino.lua ───────────────────────────────────────
def generate(output_path):
    lines = f"""\
-- casino.lua  (OpenComputers / OpenOS)
-- Generated by gen_casino.py - DO NOT EDIT BY HAND
-- Run:  python gen_casino.py

local component = require("component")
local event     = require("event")
local keyboard  = require("keyboard")
local shell     = require("shell")
local unicode   = require("unicode")

local gpu        = component.gpu
local MAX_W, MAX_H = gpu.maxResolution()
local W = math.min(120, MAX_W)
local H = math.min(40,  MAX_H)
gpu.setResolution(W, H)
local screenAddr = gpu.getScreen()

-- [CONFIG] ---------------------------------------------------
local CFG = {{
    minBet    = 1,
    maxBet    = 10,
    startBal  = 1000,
    startPot  = 5000,
    startBank = 2500,
    saveFile  = shell.getWorkingDirectory() .. "/casino_save.dat",
}}

local MULT = {{
    diamond=50, nether_star=30, emerald=20,
    ender_pearl=15, gold_ingot=10, iron_ingot=5,
}}

local ITEM_RU = {{
    diamond     = {S['diamond']},
    nether_star = {S['nether_star']},
    emerald     = {S['emerald']},
    ender_pearl = {S['ender_pearl']},
    gold_ingot  = {S['gold_ingot']},
    iron_ingot  = {S['iron_ingot']},
}}

local SYMBOLS = {{"diamond","nether_star","emerald","ender_pearl","gold_ingot","iron_ingot"}}

-- [ICONS] ----------------------------------------------------
local scriptDir = shell.getWorkingDirectory()
local loader, err = loadfile(scriptDir .. "/icons.lua")
if not loader then
    error("Cannot load icons.lua: " .. tostring(err), 0)
end
local icons = loader()
local ICW = icons.CHAR_WIDTH
local ICH = icons.CHAR_HEIGHT

-- [COLOR MAPPING]  CC blit hex -> OC 24-bit RGB ---------------
local BLIT_RGB = {{
    ["0"]=0xF0F0F0,["1"]=0xF2B233,["2"]=0xE57FD8,["3"]=0x99B2F2,
    ["4"]=0xDEDE6C,["5"]=0x7FCC19,["6"]=0xF2B2CC,["7"]=0x4C4C4C,
    ["8"]=0x999999,["9"]=0x4C99B2,["a"]=0xB266E5,["b"]=0x3366CC,
    ["c"]=0x7F664C,["d"]=0x57A64E,["e"]=0xCC4C4C,["f"]=0x111111,
}}

-- [COLORS] ---------------------------------------------------
local C = {{
    bg=0x111111, border=0x3366CC, title=0x4C99B2, header=0x4C99B2,
    text=0xF0F0F0, dim=0x999999, stat=0xDEDE6C, win=0x7FCC19,
    lose=0xCC4C4C, info=0x99B2F2, mult=0xDEDE6C,
    btnBet=0x3366CC, btnSpin=0x7FCC19, btnExit=0xCC4C4C,
    slotBord=0x3366CC, slotBg=0x111111, avatar=0x4C99B2, player=0xDEDE6C,
}}

-- [STATE] ----------------------------------------------------
local state = {{
    balance=CFG.startBal, bet=CFG.minBet,
    pot=CFG.startPot, bank=CFG.startBank,
    reels={{"diamond","emerald","gold_ingot"}},
    spinning=false, msg="", msgClr=C.text,
}}

-- [PERSISTENCE] ----------------------------------------------
local function saveGame()
    local f = io.open(CFG.saveFile,"w")
    if not f then return end
    f:write(state.balance..\"\\n\"..state.bet..\"\\n\"..state.pot..\"\\n\"..state.bank..\"\\n\")
    f:close()
end
local function loadGame()
    local f = io.open(CFG.saveFile,"r")
    if not f then return end
    state.balance = tonumber(f:read("*l")) or CFG.startBal
    state.bet     = tonumber(f:read("*l")) or CFG.minBet
    state.pot     = tonumber(f:read("*l")) or CFG.startPot
    state.bank    = tonumber(f:read("*l")) or CFG.startBank
    state.bet     = math.max(CFG.minBet, math.min(CFG.maxBet, state.bet))
    f:close()
end

-- [DRAW UTILS] -----------------------------------------------
local function put(x,y,text,fg,bg)
    gpu.setForeground(fg or C.text)
    gpu.setBackground(bg or C.bg)
    gpu.set(x,y,text)
end
local function fill(x,y,w,h,bg)
    gpu.setBackground(bg or C.bg)
    gpu.fill(x,y,w,h," ")
end
local function putCenter(y,text,fg,bg,x1,x2)
    x1=x1 or 1; x2=x2 or W
    local x=x1+math.floor((x2-x1+1-unicode.len(text))/2)
    if x<x1 then x=x1 end
    put(x,y,text,fg,bg)
end
local function drawBox(x,y,w,h,fg,bg)
    put(x,y,"+"..string.rep("-",w-2).."+",fg,bg)
    for dy=1,h-2 do put(x,y+dy,"|"..string.rep(" ",w-2).."|",fg,bg) end
    put(x,y+h-1,"+"..string.rep("-",w-2).."+",fg,bg)
end

-- Upper-half-block  U+2580  UTF-8: E2 96 80
local UPPER_BLOCK = "\\226\\150\\128"

local function drawIcon(x,y,name)
    local icon=icons[name]
    if not icon then return end
    for ri,row in ipairs(icon) do
        local cs,fg_s,bg_s=row[1],row[2],row[3]
        for col=1,ICW do
            local ch=(cs:byte(col)==143) and UPPER_BLOCK or " "
            gpu.setForeground(BLIT_RGB[fg_s:sub(col,col)] or C.bg)
            gpu.setBackground(BLIT_RGB[bg_s:sub(col,col)] or C.bg)
            gpu.set(x+col-1,y+ri-1,ch)
        end
    end
end

-- [LAYOUT] ---------------------------------------------------
local LW    = 22
local RX    = LW+2
local RW    = W-LW-1
local BOX_W = ICW+2
local BOX_H = ICH+2
local REELS_W = BOX_W*3+4
local REELS_X = LW+1+math.floor((W-LW-1-REELS_W)/2)
local BTN_Y   = H-2
local BET_Y   = H-3
local REELS_Y = BET_Y-1-BOX_H

-- [BUTTONS] --------------------------------------------------
local buttons={{}}
local function regBtn(x1,y1,x2,y2,action)
    table.insert(buttons,{{x1=x1,y1=y1,x2=x2,y2=y2,action=action}})
end
local function calcBetBtns()
    local defs={{
        {{"-10","bet:-10"}},{{"- 5","bet:-5"}},{{"-1","bet:-1"}},
        {{{S['stavka']}..state.bet,"spin"}},
        {{"+1","bet:1"}},{{"+5","bet:5"}},{{"+10","bet:10"}},
    }}
    local totalW=-1
    for _,d in ipairs(defs) do totalW=totalW+unicode.len(d[1])+3 end
    local cx=LW+1+math.floor((W-LW-1-totalW)/2)
    local res={{}}
    for _,d in ipairs(defs) do
        local lbl="["..d[1].."]"
        local vl=unicode.len(lbl)
        table.insert(res,{{x=cx,y=BTN_Y,label=lbl,vlen=vl,action=d[2],isSpin=(d[2]=="spin")}})
        cx=cx+vl+1
    end
    return res
end
local function handleTouch(tx,ty)
    for _,b in ipairs(buttons) do
        if tx>=b.x1 and tx<=b.x2 and ty>=b.y1 and ty<=b.y2 then return b.action end
    end
end

-- [FRAME] ----------------------------------------------------
local function drawFrame()
    fill(1,1,W,H,C.bg)
    put(1,1,"+"..string.rep("-",W-2).."+",C.border,C.bg)
    for y=2,H-1 do put(1,y,"|",C.border,C.bg); put(W,y,"|",C.border,C.bg) end
    put(1,H,"+"..string.rep("-",W-2).."+",C.border,C.bg)
    for y=1,H do put(LW+1,y,"|",C.border,C.bg) end
    put(LW+1,1,"+",C.border,C.bg); put(LW+1,H,"+",C.border,C.bg)
end

-- [LEFT PANEL] -----------------------------------------------
local function drawLeft()
    local x=2
    put(x,2, {S['gen_info']},    C.header,C.bg)
    put(x,4, {S['risk1']},       C.dim,   C.bg)
    put(x,5, {S['risk2']},       C.dim,   C.bg)
    put(x,6, {S['noret1']},      C.dim,   C.bg)
    put(x,7, {S['noret2']},      C.dim,   C.bg)
    put(x,9, {S['total']},       C.text,  C.bg)
    put(x,10,"  "..state.pot..{S['cur']},  C.stat,  C.bg)
    put(x,12,{S['bank']},        C.text,  C.bg)
    put(x,13,"  "..state.bank..{S['cur']}, C.stat,  C.bg)
    put(x,15,string.rep("-",LW-2),C.border,C.bg)
    put(x,16,{S['avatar']},      C.avatar,C.bg)
    put(x,18,{S['player_lbl']},  C.text,  C.bg)
    local addr=""
    pcall(function() addr=tostring(component.computer.address()):sub(1,LW-4) end)
    put(x,19,"  "..addr,         C.player,C.bg)
    put(x,21,{S['balance_lbl']}, C.text,  C.bg)
    put(x,22,"  "..state.balance..{S['cur']},C.stat,C.bg)
    fill(x,23,LW-2,1,C.bg)
    if state.spinning then
        put(x,23,{S['spinning']},C.win,C.bg)
    elseif state.msg~="" then
        local m=state.msg
        if unicode.len(m)>LW-2 then m=unicode.sub(m,1,LW-2) end
        put(x,23,m,state.msgClr,C.bg)
    else
        put(x,23,{S['ready']},C.dim,C.bg)
    end
    put(3,H-2,{S['exit_btn']},C.btnExit,C.bg)
end

-- [RIGHT PANEL] ----------------------------------------------
local function drawRight()
    putCenter(2,{S['title']},C.title,C.bg,LW+2,W-1)
    put(RX,4, {S['win_hdr']},    C.header,C.bg)
    put(RX,5, {S['win_formula']},C.text,  C.bg)
    put(RX,6, {S['w_edges']},    C.info,  C.bg)
    put(RX,8, {S['row_iron']},   C.mult,  C.bg)
    put(RX,9, {S['row_pearl']},  C.mult,  C.bg)
    put(RX,10,{S['min_bet']}.." "..CFG.minBet..{S['cur']}.."   "..{S['max_bet']}.." "..CFG.maxBet..{S['cur']},C.dim,C.bg)
end

-- [REELS] ----------------------------------------------------
local function drawReels()
    for i=1,3 do
        local bx=REELS_X+(i-1)*(BOX_W+2)
        drawBox(bx,REELS_Y,BOX_W,BOX_H,C.slotBord,C.bg)
        fill(bx+1,REELS_Y+1,ICW,ICH,C.slotBg)
        drawIcon(bx+1,REELS_Y+1,state.reels[i])
    end
end

-- [BET BAR] --------------------------------------------------
local function drawBetBar()
    fill(LW+2,BET_Y-1,W-LW-2,1,C.bg)
    putCenter(BET_Y-1,{S['spin_for']}.." "..state.bet..{S['cur']},C.text,C.bg,LW+2,W-1)
    local btns=calcBetBtns()
    buttons={{}}
    regBtn(3,H-2,unicode.len({S['exit_btn']})+2,H-2,"exit")
    fill(LW+2,BTN_Y,W-LW-2,1,C.bg)
    for _,b in ipairs(btns) do
        put(b.x,b.y,b.label,b.isSpin and C.btnSpin or C.btnBet,C.bg)
        regBtn(b.x,b.y,b.x+b.vlen-1,b.y,b.action)
    end
end

local function redraw()
    drawFrame(); drawLeft(); drawRight(); drawReels(); drawBetBar()
end
local function partRedraw()
    drawLeft(); drawReels(); drawBetBar()
end

-- [GAME LOGIC] -----------------------------------------------
local function checkWin(r)
    local a,b,c=r[1],r[2],r[3]
    if a==b and b==c then
        local m=MULT[a] or 5
        return m, {S['three_pfx']}..ITEM_RU[a]..{S['bonus_pfx']}..m
    end
    if a==b or b==c then return 2,{S['w_adj_msg']} end
    if a==c          then return 1,{S['w_edge_msg']} end
    return 0,{S['no_luck']}
end

local function animSpin(final)
    state.spinning=true
    local stops={{12,16,20}}
    for step=1,20 do
        for i=1,3 do
            state.reels[i]=(step<stops[i]) and SYMBOLS[math.random(#SYMBOLS)] or final[i]
        end
        drawReels(); drawLeft(); os.sleep(0.05)
    end
    state.reels=final; state.spinning=false
end

local function doSpin()
    if state.spinning then return end
    if state.balance<state.bet then
        state.msg={S['no_coins']}; state.msgClr=C.lose; partRedraw(); return
    end
    state.balance=state.balance-state.bet
    state.pot=state.pot+state.bet
    state.bank=state.bank+math.floor(state.bet*0.4)
    state.msg=""
    local final={{}}
    for i=1,3 do final[i]=SYMBOLS[math.random(#SYMBOLS)] end
    animSpin(final)
    local mult,msg=checkWin(final)
    if mult>0 then
        local gain=state.bet*mult
        state.balance=state.balance+gain
        state.bank=math.max(0,state.bank-gain)
        state.msg=msg..{S['coin_sfx']}; state.msgClr=C.win
    else
        state.msg=msg; state.msgClr=C.lose
    end
    saveGame(); partRedraw()
end

local function changeBet(d)
    state.bet=math.max(CFG.minBet,math.min(CFG.maxBet,state.bet+d))
end

-- [MAIN LOOP] ------------------------------------------------
local function main()
    math.randomseed(os.time())
    loadGame()
    gpu.setBackground(C.bg); gpu.fill(1,1,W,H," ")
    redraw()
    while true do
        local etype,p1,p2,p3=event.pull()
        if etype=="touch" and p1==screenAddr then
            local a=handleTouch(p2,p3)
            if a=="exit" then break
            elseif a=="spin" then doSpin()
            elseif a and a:sub(1,4)=="bet:" then
                changeBet(tonumber(a:sub(5)) or 0); drawBetBar()
            end
        elseif etype=="key_down" then
            local code=p3
            if code==keyboard.keys.space or code==keyboard.keys.enter then doSpin()
            elseif code==keyboard.keys.left  then changeBet(-1); drawBetBar()
            elseif code==keyboard.keys.right then changeBet(1);  drawBetBar()
            elseif code==keyboard.keys.q     then break
            end
        elseif etype=="interrupted" then break
        end
    end
    saveGame()
    gpu.setBackground(C.bg); gpu.setForeground(C.text)
    gpu.fill(1,1,W,H," ")
    gpu.set(1,1,"Bye!")
end

main()
"""
    # Write as pure ASCII bytes with LF-only line endings (required by OC Lua).
    with open(output_path, "wb") as f:
        f.write(lines.encode("ascii").replace(b"\r\n", b"\n").replace(b"\r", b"\n"))
    print(f"  casino.lua written ({len(lines)} bytes)")


# ─── main ─────────────────────────────────────────────────────
if __name__ == "__main__":
    script_dir  = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(script_dir, "casino.lua")
    print("Generating casino.lua ...")
    generate(output_path)
    print("Done!  Upload casino.lua and icons.lua to your OC computer.")
    print("Tip: also re-run convert_icons.py to regenerate icons.lua with new smaller icon size.")
