-- icons.lua
-- Auto-generated by convert_icons.py  --  DO NOT EDIT BY HAND
--
-- Half-pixel blit icons for ComputerCraft casino.
-- Each icon[i] = { chars_string, fg_hex_string, bg_hex_string }
-- Use with:  mon.blit(row[1], row[2], row[3])
-- Upper-half-block char (\143): fg=top pixel, bg=bottom pixel.

local M = {}
M.CHAR_WIDTH  = 5
M.CHAR_HEIGHT = 4

M.diamond = {
  { "  \143  ", "fffff", "ff3ff" },
  { " \143\143  ", "f505f", "f055f" },
  { "\143\143 \143\143", "d05d9", "f559f" },
  { " \143\143\143 ", "f959f", "ff9ff" },
}

M.emerald = {
  { " \143\143\143 ", "fffff", "f359f" },
  { " \143 \143 ", "f45df", "f559f" },
  { " \143\143\143 ", "f559f", "fdddf" },
  { " \143\143\143 ", "f9d9f", "fffff" },
}

M.ender_pearl = {
  { " \143\143\143 ", "fffff", "fbbbf" },
  { "\143\143\143 \143", "fd77f", "bbf77" },
  { "\143\143\143\143\143", "b7fbb", "fb7df" },
  { " \143\143\143 ", "f7bbf", "fffff" },
}

M.gold_ingot = {
  { "  \143\143 ", "fffff", "ff11f" },
  { "\143\143\143 \143", "11044", "40441" },
  { "  \143\143\143", "44411", "441ec" },
  { " \143\143  ", "f1eff", "fffff" },
}

M.iron_ingot = {
  { "  \143\143 ", "fffff", "ff83f" },
  { "\143\143\143\143\143", "83403", "40048" },
  { "\143\143\143\143 ", "348ac", "88cbc" },
  { " \143\143  ", "f87ff", "fffff" },
}

M.nether_star = {
  { "  \143  ", "fffff", "ff9ff" },
  { " \143\143\143 ", "ff3ff", "f343f" },
  { " \143\143\143 ", "f303f", "ff3ff" },
  { "  \143  ", "ff8ff", "fffff" },
}

return M
