-- icons.lua
-- Auto-generated by convert_icons.py  --  DO NOT EDIT BY HAND
--
-- Half-pixel blit icons for ComputerCraft casino.
-- Each icon[i] = { chars_string, fg_hex_string, bg_hex_string }
-- Use with:  mon.blit(row[1], row[2], row[3])
-- Upper-half-block char (\143): fg=top pixel, bg=bottom pixel.

local M = {}
M.CHAR_WIDTH  = 9
M.CHAR_HEIGHT = 8

M.diamond = {
  { "         ", "fffffffff", "fffffffff" },
  { "   \143\143\143   ", "fffb9bfff", "fff405fff" },
  { "  \143\143  \143  ", "ff30559ff", "ff55555ff" },
  { " \143  \143    ", "f9050559f", "fd055559f" },
  { "   \143  \143  ", "f3555559f", "f35055d9f" },
  { " \143\143 \143\143   ", "f3055959f", "f9559d59f" },
  { "    \143    ", "ff95d59ff", "ff95559ff" },
  { "   \143\143\143   ", "fffb9bfff", "fffffffff" },
}

M.emerald = {
  { "         ", "fffffffff", "fffffffff" },
  { "  \143\143\143\143\143  ", "fffdddfff", "ff9055bff" },
  { " \143\143    \143 ", "ff50559ff", "fb005597f" },
  { " \143   \143\143  ", "fd5559d7f", "f9555d97f" },
  { "         ", "f9555d97f", "f9555d97f" },
  { " \143\143\143\143  \143 ", "f9555dd7f", "ff9dbddff" },
  { "  \143\143\143\143\143  ", "ff9dddbff", "fffb9bfff" },
  { "         ", "fffffffff", "fffffffff" },
}

M.ender_pearl = {
  { "         ", "fffffffff", "fffffffff" },
  { "  \143\143 \143\143  ", "fff7b7fff", "ff79b97ff" },
  { " \143\143\143\143  \143 ", "ff9d77bff", "f759f7b7f" },
  { "  \143 \143\143\143  ", "fb9f7fb7f", "fb7ff777f" },
  { " \143 \143\143 \143\143 ", "fbb7ffbbf", "f7bf7fd7f" },
  { " \143 \143 \143 \143 ", "f7b777dbf", "ffbb79dff" },
  { "  \143\143 \143\143  ", "ff77bdbff", "ffffbffff" },
  { "         ", "fffffffff", "fffffffff" },
}

M.gold_ingot = {
  { "         ", "fffffffff", "fffffffff" },
  { "    \143\143\143\143 ", "fffffc1ff", "ffff1441f" },
  { "\143\143\143\143    \143", "ffc14444f", "c10444441" },
  { "       \143 ", "444444401", "444444411" },
  { "\143\143  \143\143\143 \143", "104444118", "444411211" },
  { "\143  \143\143\143\143\143\143", "1441211ce", "e4421ceff" },
  { " \143\143\143\143\143   ", "f141e7fff", "ff27fffff" },
  { "         ", "fffffffff", "fffffffff" },
}

M.iron_ingot = {
  { "         ", "fffffffff", "fffffffff" },
  { "    \143\143\143\143 ", "fffffccff", "ffff8308f" },
  { "\143\143\143\143\143\143 \143\143", "ffc80408f", "c84043048" },
  { "\143 \143\143\143\143\143\143\143", "300304008", "60444068c" },
  { " \143\143\143\143\143\143\143\143", "844048bcc", "8303ccc98" },
  { "\143\143\143 \143\143\143\143\143", "838cc9cc7", "783c8c7ff" },
  { " \143\143\143\143\143   ", "f88cb7fff", "ffc7fffff" },
  { "         ", "fffffffff", "fffffffff" },
}

M.nether_star = {
  { "         ", "fffffffff", "fffffffff" },
  { "    \143    ", "fffffffff", "ffff8ffff" },
  { "   \143\143    ", "ffff38fff", "fff948fff" },
  { "  \143\143 \143\143\143 ", "fff8037ff", "ff34043cf" },
  { " \143\143\143 \143\143\143 ", "f9404449f", "ffb343bff" },
  { "   \143\143    ", "fff908fff", "ffff38fff" },
  { "    \143    ", "ffff8ffff", "ffffcffff" },
  { "         ", "fffffffff", "fffffffff" },
}

return M
