-- icons.lua
-- Auto-generated by convert_icons.py  --  DO NOT EDIT BY HAND
--
-- Half-pixel blit icons for ComputerCraft casino.
-- Each icon[i] = { chars_string, fg_hex_string, bg_hex_string }
-- Use with:  mon.blit(row[1], row[2], row[3])
-- Upper-half-block char (\143): fg=top pixel, bg=bottom pixel.

local M = {}
M.CHAR_WIDTH  = 7
M.CHAR_HEIGHT = 8

M.diamond = {
  { "       ", "fffffff", "fffffff" },
  { "  \143\143\143  ", "fff9fff", "ff305ff" },
  { " \143   \143 ", "ff055ff", "fd0559f" },
  { " \143\143\143   ", "f35059f", "f50559f" },
  { "  \143    ", "f55559f", "f50559f" },
  { "   \143\143  ", "f555d9f", "f55d59f" },
  { " \143\143\143\143\143 ", "f95d59f", "ff95dff" },
  { "  \143\143\143  ", "ffb9bff", "fffffff" },
}

M.emerald = {
  { "       ", "fffffff", "fffffff" },
  { "  \143\143\143  ", "ffdd9ff", "ff45dff" },
  { " \143  \143\143 ", "fd055bf", "f305d9f" },
  { " \143     ", "f555dbf", "fd55dbf" },
  { "       ", "fd55dbf", "fd55dbf" },
  { " \143\143\143 \143 ", "fd55ddf", "f9d9d9f" },
  { "  \143\143\143  ", "ffdddff", "ffb9bff" },
  { "       ", "fffffff", "fffffff" },
}

M.ender_pearl = {
  { "       ", "fffffff", "fffffff" },
  { "  \143\143   ", "ff7b7ff", "ffb97ff" },
  { " \143  \143  ", "fbd7b7f", "fdd777f" },
  { "  \143    ", "fbbf77f", "fbff77f" },
  { "       ", "fb7f7bf", "fb7f7bf" },
  { "  \143 \143\143 ", "f777bdf", "f7b7d9f" },
  { "  \143\143\143  ", "ff799ff", "fff7fff" },
  { "       ", "fffffff", "fffffff" },
}

M.gold_ingot = {
  { "       ", "fffffff", "fffffff" },
  { "   \143\143\143 ", "ffff28f", "fff844f" },
  { "\143\143\143    ", "fe14441", "c444441" },
  { "      \143", "4444444", "4444441" },
  { "\143\143 \143 \143\143", "4440112", "1041121" },
  { "   \143\143\143\143", "141218e", "1411cef" },
  { " \143\143\143   ", "f11cfff", "f8effff" },
  { "       ", "fffffff", "fffffff" },
}

M.iron_ingot = {
  { "       ", "fffffff", "fffffff" },
  { "   \143\143\143 ", "ffffc8f", "fff843f" },
  { "\143\143\143 \143\143\143", "f78403c", "c304603" },
  { "\143 \143 \143\143\143", "4060403", "303008c" },
  { "\143 \143\143\143\143\143", "34048bc", "8469cc8" },
  { "\143 \143 \143\143\143", "83ccc97", "c38cb7f" },
  { " \143\143\143   ", "f887fff", "fc7ffff" },
  { "       ", "fffffff", "fffffff" },
}

M.nether_star = {
  { "       ", "fffffff", "fffffff" },
  { "   \143   ", "fffffff", "fff8fff" },
  { "   \143\143  ", "fff8fff", "fff48ff" },
  { " \143\143 \143\143 ", "ff908ff", "f84049f" },
  { " \143\143\143\143\143 ", "f80408f", "ff8097f" },
  { "  \143\143\143  ", "ffb48ff", "fff39ff" },
  { "   \143   ", "fff8fff", "fffcfff" },
  { "       ", "fffffff", "fffffff" },
}

return M
